### ISSUE TITLE
Libary usage

### ISSUE THREAD

**Issue by DavixDevelop** [romgerman/DiscordUWP8#1]
Hey, could you write a in depth instructions on how to use this libary? Like, getting token, etc...

**Comment by romgerman** [comment]
Hi. This library is unmaintained because currently i'm working on my hitbox library.
First you must login with your email & password `client.Login(email, password)` and you will get your account token. Then you can store the token and use it in `client.Login(token)` method. Then you can use any method you want.
I'm not sure if this library still work correctly but you can give it a try if you want. Sorry.

**Comment by DavixDevelop** [comment]
Hi. Thanks for the quick response :) That's right what I needed. If I'll need something, I will just modify the library. And when I will finish this app, I hope, I'll be sure to credit you in it. I decided to use your library, because It was the only one that Is compatible with UWP. Discord.Net and DiscordSharp won't work with UWP. Anyways, thank you for the quick reply again :)

**Comment by romgerman** [comment]
> Discord.Net and DiscordSharp won't work with UWP
Yeah. That's why i'm started making this library.
